# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "ruby_gmail_xoauth"
  s.version = "0.3.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Chris Duesing", "BehindLogic", "Nicolas Fouch\u{e9}"]
  s.date = "2012-02-13"
  s.description = "A Rubyesque interface to Gmail, with all the tools you'll need. Search, read and send multipart emails; archive, mark as read/unread, delete emails; and manage labels."
  s.email = "chris.duesing@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.markdown"
  ]
  s.files = [
    ".autotest",
    "History.txt",
    "LICENSE",
    "Manifest.txt",
    "README.markdown",
    "Rakefile",
    "VERSION",
    "lib/gmail.rb",
    "lib/gmail/gmail_base.rb",
    "lib/gmail/imap_xoauth_authenticator.rb",
    "lib/gmail/mailbox.rb",
    "lib/gmail/message.rb",
    "lib/gmail/oauth_string.rb",
    "lib/gmail/smtp_xoauth_authenticator.rb",
    "lib/gmail_xoauth.rb",
    "lib/smtp_tls.rb",
    "ruby_gmail_xoauth.gemspec",
    "test/helper.rb",
    "test/test_gmail.rb",
    "test/test_helper.rb",
    "test/test_imap_xoauth_authenticator.rb",
    "test/test_oauth_string.rb",
    "test/test_smtp_xoauth_authenticator.rb"
  ]
  s.homepage = "https://github.com/chrisduesing/ruby_gmail_xoauth"
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.10"
  s.summary = "A Rubyesque interface to Gmail, with all the tools you'll need."

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<shared-mime-info>, [">= 0"])
      s.add_runtime_dependency(%q<mail>, [">= 2.2.1"])
      s.add_runtime_dependency(%q<mime>, [">= 0.1"])
      s.add_runtime_dependency(%q<oauth>, [">= 0.3.6"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
    else
      s.add_dependency(%q<shared-mime-info>, [">= 0"])
      s.add_dependency(%q<mail>, [">= 2.2.1"])
      s.add_dependency(%q<mime>, [">= 0.1"])
      s.add_dependency(%q<oauth>, [">= 0.3.6"])
      s.add_dependency(%q<shoulda>, [">= 0"])
    end
  else
    s.add_dependency(%q<shared-mime-info>, [">= 0"])
    s.add_dependency(%q<mail>, [">= 2.2.1"])
    s.add_dependency(%q<mime>, [">= 0.1"])
    s.add_dependency(%q<oauth>, [">= 0.3.6"])
    s.add_dependency(%q<shoulda>, [">= 0"])
  end
end

